/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef }  from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const mesh = useRef()
  const { nodes } = useGLTF('meta.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-2, -1, -3]} rotation={[1.6,0.01, 0.50]} scale={100}>
        <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
        <pointLight intensity={4} decay={4} />
      </group>
    </group>
  )
}

useGLTF.preload('/meta.gltf')
